apiVersion: v1
kind: PersistentVolume
metadata:
  name: agwc-pv
  labels:
    type: local
    app.kubernetes.io/component: agwc-claim
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/magma"
