---
# Leave repository and daemon.json in place
- name: Remove docker.io and containerd
  become: yes
  apt:
    name: 
    - docker.io=20.10.21-0ubuntu1~20.04.2
    - containerd
    state: absent

# - name: Install Docker Module for Python
  # pip:
  #  name: docker
  # shell:
  #  curl https://releases.rancher.com/install-docker/{{ docker_version }}.sh | sh


