{{- if .Values.persistence.enabled}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
  - {{ .Values.persistence.accessMode | quote}}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  hostPath:
    path: "{{.Values.persistence.location}}"
  storageClassName: {{ template "influxdb.fullname" . }}
{{- end }}
