{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: {{ template "influxdb.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote}}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
{{- if (eq "fullname" .Values.persistence.storageClass) }}
  storageClassName: "{{ template "influxdb.fullname" . }}"
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
{{- end -}}
{{- end -}}
