{{- if .Values.persistence.enabled}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}
