---
# Must run common-system first
- name: Install Magma Orchestrator
  hosts: all
  roles:
    - role: metallb
    - role: openebs
    - role: postgresql
    - role: secrets
    - role: orc8r
    - role: prometheus_cache_cleanup
    - role: haproxy
    - role: elasticsearch
    - role: fluentd
    - role: dns
