---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: agwc-claim
  name: agwc-claim
  namespace: magma
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
